# Generated by Django 5.2 on 2025-04-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_review_section_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_section',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review_section',
            name='review',
            field=models.TextField(max_length=100),
        ),
    ]
