# Generated by Django 5.2 on 2025-04-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_review_section_designation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review_section',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
