# Generated by Django 5.2 on 2025-04-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_herobackgroundimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herobackgroundimage',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='herobackgroundimage',
            name='active',
        ),
        migrations.RemoveField(
            model_name='herobackgroundimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='herobackgroundimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='herobackgroundimage',
            name='image',
            field=models.ImageField(upload_to='hero-backgrounds/'),
        ),
    ]
