# Generated by Django 5.2 on 2025-05-07 13:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_alter_herobackgroundimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobackgroundimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='review_section',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
